(function(){
"use strict";
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=url=>{if(!url)return'#';try{const u=new URL(url,location.href);return['http:','https:','mailto:','tel:'].includes(u.protocol)?u.href:'#'}catch{return'#'}};
const LOCAL_IMAGES={'sis-mini-factory':'assets/images/cabinet-open.jpg','plc-esp32-motor-control':'assets/images/motor-control.jpg','fruit-vegetable-recognition':'assets/images/fruit-recognition.jpg','solar-oven':'assets/images/solar-oven.svg'};
const UI={
 en:{home:'Home',projects:'Projects',skills:'Skills',contact:'Contact',viewProjects:'View Projects',downloadCV:'Download CV',admin:'Admin',backHome:'Back to Home',loading:'Loading…',notFoundPage:'Page not found.',notFoundProject:'Project not found or not published.',noProjects:'No published projects yet.',aboutProject:'About the Project',projectImages:'Project Images',projectInfo:'Project Information',category:'Category',date:'Date',openProject:'Open Project',watchVideo:'Watch Video',downloadReport:'Download Report',linksLater:'Links will be added later.',section:'SECTION'},
 fr:{home:'Accueil',projects:'Projets',skills:'Compétences',contact:'Contact',viewProjects:'Voir les projets',downloadCV:'Télécharger le CV',admin:'Administration',backHome:'Retour à l’accueil',loading:'Chargement…',notFoundPage:'Page introuvable.',notFoundProject:'Projet introuvable ou non publié.',noProjects:'Aucun projet publié.',aboutProject:'À propos du projet',projectImages:'Images du projet',projectInfo:'Informations du projet',category:'Catégorie',date:'Date',openProject:'Ouvrir le projet',watchVideo:'Voir la vidéo',downloadReport:'Télécharger le rapport',linksLater:'Les liens seront ajoutés ultérieurement.',section:'SECTION'},
 ar:{home:'الرئيسية',projects:'المشاريع',skills:'المهارات',contact:'تواصل',viewProjects:'مشاهدة المشاريع',downloadCV:'تحميل CV',admin:'لوحة الإدارة',backHome:'العودة للرئيسية',loading:'جارٍ التحميل…',notFoundPage:'الصفحة غير موجودة.',notFoundProject:'المشروع غير موجود أو غير منشور.',noProjects:'لا توجد مشاريع منشورة.',aboutProject:'عن المشروع',projectImages:'صور المشروع',projectInfo:'معلومات المشروع',category:'التصنيف',date:'التاريخ',openProject:'فتح المشروع',watchVideo:'مشاهدة الفيديو',downloadReport:'تحميل التقرير',linksLater:'ستضاف الروابط لاحقًا.',section:'قسم'}
};
let LANG=localStorage.getItem('larbi_portfolio_language')||'en';if(!['en','fr','ar'].includes(LANG))LANG='en';
const suffix={en:'En',fr:'Fr',ar:'Ar'};
function tr(o,key){if(!o)return'';return o[key+suffix[LANG]]||o[key+'En']||o[key+'Fr']||o[key+'Ar']||o[key]||''}
function t(k){return UI[LANG][k]||UI.en[k]||k}
function normalizeImageUrl(url){const v=String(url||'').trim();if(!v)return'';const ps=[/[?&]id=([A-Za-z0-9_-]{10,})/,/\/d\/([A-Za-z0-9_-]{10,})/,/googleusercontent\.com\/d\/([A-Za-z0-9_-]{10,})/];for(const p of ps){const m=v.match(p);if(m)return`https://drive.google.com/thumbnail?id=${encodeURIComponent(m[1])}&sz=w2000`}return v}
function imageForProject(p){return normalizeImageUrl(p.mainImage)||LOCAL_IMAGES[p.slug||p.id]||'assets/images/solar-oven.svg'}
function loadJsonp(url,timeout=16000){return new Promise((res,rej)=>{const cb='__larbi_'+Date.now()+'_'+Math.floor(Math.random()*1e4),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('timeout')),timeout);function done(e,d){clearTimeout(timer);try{delete window[cb]}catch{}s.remove();e?rej(e):res(d)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error('network'));s.src=url+(url.includes('?')?'&':'?')+'callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(s)})}
const FALLBACK={settings:{brandText:'Larbi Portfolio',accentColor:'#0aa8ff',accentColor2:'#54d4ff',siteTitleEn:'Tlili Mohammed Larbi | Engineering Portfolio',siteTitleFr:'Tlili Mohammed Larbi | Portfolio d’ingénierie',siteTitleAr:'تليلي محمد العربي | محفظة هندسية',heroBadgeEn:'Embedded Systems & Industrial Automation Engineer',heroBadgeFr:'Ingénieur en systèmes embarqués et automatisation industrielle',heroBadgeAr:'مهندس أنظمة مدمجة وأتمتة صناعية',footerTextEn:'© 2026 Tlili Mohammed Larbi. All rights reserved.',footerTextFr:'© 2026 Tlili Mohammed Larbi. Tous droits réservés.',footerTextAr:'© 2026 تليلي محمد العربي. جميع الحقوق محفوظة.'},profile:{nameEn:'Tlili Mohammed Larbi',nameFr:'Tlili Mohammed Larbi',nameAr:'تليلي محمد العربي',roleEn:'Embedded Systems & Industrial Automation Portfolio',roleFr:'Portfolio en systèmes embarqués et automatisation industrielle',roleAr:'مهندس أنظمة مدمجة وأتمتة صناعية',bioEn:'Embedded systems and industrial automation specialist developing practical PLC, ESP32, HMI and IoT solutions.',bioFr:'Spécialiste des systèmes embarqués et de l’automatisation industrielle.',bioAr:'متخصص في الأنظمة المدمجة والأتمتة الصناعية.',profileImageURL:'assets/images/profile-hero.png'},projects:[],pages:[],sections:[],technologies:[],skillGroups:[],skills:[]};
async function loadData(){const u=window.PORTFOLIO_CONFIG&&window.PORTFOLIO_CONFIG.apiUrl;if(!u)return FALLBACK;try{const d=await loadJsonp(u);if(!d||!d.ok)throw 0;return{settings:Object.assign({},FALLBACK.settings,d.settings||{}),profile:Object.assign({},FALLBACK.profile,d.profile||{}),projects:Array.isArray(d.projects)?d.projects:[],pages:Array.isArray(d.pages)?d.pages:[],sections:Array.isArray(d.sections)?d.sections:[],technologies:Array.isArray(d.technologies)?d.technologies:[],skillGroups:Array.isArray(d.skillGroups)?d.skillGroups:[],skills:Array.isArray(d.skills)?d.skills:[]}}catch(e){console.warn('fallback',e);return FALLBACK}}
function setLanguageDocument(){document.documentElement.lang=LANG;document.documentElement.dir=LANG==='ar'?'rtl':'ltr';const sel=document.getElementById('languageSelect');if(sel)sel.value=LANG}
function applyTheme(s){if(s.accentColor)document.documentElement.style.setProperty('--primary',s.accentColor);if(s.accentColor2)document.documentElement.style.setProperty('--primary2',s.accentColor2);document.title=tr(s,'siteTitle')||'Larbi Portfolio';document.querySelectorAll('#brandText').forEach(x=>x.textContent=s.brandText||'Larbi Portfolio');document.querySelectorAll('#footerText').forEach(x=>x.textContent=tr(s,'footerText'));}
function translateStatic(){const map={navHome:'home',navProjects:'projects',navSkills:'skills',navContact:'contact',projectsButton:'viewProjects',cvBtn:'downloadCV',adminLink:'admin',backHome:'backHome'};Object.keys(map).forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=t(map[id])});document.querySelectorAll('[data-loading]').forEach(e=>e.textContent=t('loading'));}
function renderNav(pages){const html=pages.filter(p=>p.published!==false&&p.showInMenu!==false).sort((a,b)=>(a.menuOrder||999)-(b.menuOrder||999)).map(p=>`<a href="page.html?slug=${encodeURIComponent(p.slug)}">${esc(tr(p,'menuTitle')||tr(p,'title'))}</a>`).join('');document.querySelectorAll('#dynamicNav').forEach(x=>x.innerHTML=html)}
function parseLines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}function paragraphHtml(v){return parseLines(v).map(x=>`<p>${esc(x)}</p>`).join('')}
function techHtml(items){return items.filter(x=>x.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999)).map(x=>{const name=tr(x,'name'),sub=tr(x,'subtitle'),visual=x.logoUrl?`<img class="tech-logo" src="${esc(normalizeImageUrl(x.logoUrl))}" alt="${esc(name)}">`:`<span>${esc(x.symbol||name.slice(0,3))}</span>`;const inner=`<div class="tech-icon">${visual}</div><div><strong>${esc(name)}</strong><small>${esc(sub)}</small></div>`;return x.linkUrl?`<a class="tech-chip" href="${safeUrl(x.linkUrl)}" target="_blank">${inner}</a>`:`<div class="tech-chip">${inner}</div>`}).join('')}
function projectCard(p){const title=tr(p,'title'),category=tr(p,'category'),short=tr(p,'shortDescription');return`<a class="project-card" href="project.html?slug=${encodeURIComponent(p.slug||p.id)}"><div class="project-image"><img src="${esc(imageForProject(p))}" alt="${esc(title)}" onerror="this.src='${esc(LOCAL_IMAGES[p.slug||p.id]||'assets/images/solar-oven.svg')}'"></div><div class="project-body"><span class="project-category">${esc(category)}</span><h3>${esc(title)}</h3><p>${esc(short)}</p><div class="tags">${(p.tags||[]).slice(0,4).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div></a>`}
function typeLabel(type){const labels={projects:{en:'PROJECTS',fr:'PROJETS',ar:'المشاريع'},skills:{en:'SKILLS',fr:'COMPÉTENCES',ar:'المهارات'},cards:{en:'CARDS',fr:'CARTES',ar:'بطاقات'},rich:{en:'CONTENT',fr:'CONTENU',ar:'محتوى'},stats:{en:'STATS',fr:'STATISTIQUES',ar:'إحصائيات'},timeline:{en:'TIMELINE',fr:'PARCOURS',ar:'المسار'},gallery:{en:'GALLERY',fr:'GALERIE',ar:'معرض'},cta:{en:'CONTACT',fr:'CONTACT',ar:'تواصل'}};return(labels[type]&&labels[type][LANG])||t('section')}
function sectionTitle(s){return`<div class="section-title"><span class="kicker">${esc(typeLabel(s.type))}</span><h2>${esc(tr(s,'title'))}</h2>${tr(s,'subtitle')?`<p>${esc(tr(s,'subtitle'))}</p>`:''}</div>`}
function skillsHtml(groups,skills){return groups.filter(g=>g.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999)).map(g=>{const items=skills.filter(s=>s.visible!==false&&s.groupId===g.id).sort((a,b)=>(a.order||999)-(b.order||999));const icon=g.iconUrl?`<img src="${esc(normalizeImageUrl(g.iconUrl))}" alt="">`:`<span>${esc(g.iconText||'•')}</span>`;return`<article class="skill-box"><div class="skill-title-row"><div class="skill-group-icon">${icon}</div><h3>${esc(tr(g,'title'))}</h3></div><ul>${items.map(s=>`<li>${s.iconUrl?`<img class="skill-item-icon" src="${esc(normalizeImageUrl(s.iconUrl))}" alt="">`:''}${esc(tr(s,'name'))}</li>`).join('')}</ul></article>`}).join('')}
function renderSection(s,d){const type=s.type||'rich',cls='section',sectionId=(s.pageSlug==='home'&&type==='cta')?'contact':(s.id||type);let body='';if(type==='projects'){const ps=d.projects.filter(p=>p.published!==false&&p.featured!==false).sort((a,b)=>(a.order||999)-(b.order||999));body=sectionTitle(s)+`<div class="projects-grid" id="projects">${ps.length?ps.map(projectCard).join(''):`<div class="empty-state">${t('noProjects')}</div>`}</div>`}else if(type==='skills'){body=sectionTitle(s)+`<div class="skills-grid" id="skills">${skillsHtml(d.skillGroups,d.skills)}</div>`}else if(type==='cards'){body=sectionTitle(s)+`<div class="cards-grid">${parseLines(tr(s,'itemsText')).map(l=>{const[a,b,img,url,tags]=l.split('|'),inner=`${img?`<img src="${esc(normalizeImageUrl(img))}" alt="">`:''}<h3>${esc(a||'')}</h3><p>${esc(b||'')}</p>${tags?`<div class="tags">${tags.split(';').map(x=>`<span class="tag">${esc(x.trim())}</span>`).join('')}</div>`:''}`;return url?`<a class="generic-card" href="${safeUrl(url)}">${inner}</a>`:`<article class="generic-card">${inner}</article>`}).join('')}</div>`}else if(type==='stats'){body=sectionTitle(s)+`<div class="stats-grid">${parseLines(tr(s,'itemsText')).map(l=>{const[n,a]=l.split('|');return`<div class="stat-card"><strong>${esc(n||'')}</strong><span>${esc(a||'')}</span></div>`}).join('')}</div>`}else if(type==='timeline'){body=sectionTitle(s)+`<div class="timeline">${parseLines(tr(s,'itemsText')).map(l=>{const[y,a,b]=l.split('|');return`<article class="timeline-item"><div class="timeline-year">${esc(y||'')}</div><div><h3>${esc(a||'')}</h3><p>${esc(b||'')}</p></div></article>`}).join('')}</div>`}else if(type==='gallery'){body=sectionTitle(s)+`<div class="gallery-grid">${parseLines(tr(s,'itemsText')).map(l=>{const[i,c]=l.split('|');return`<figure class="gallery-item"><img src="${esc(normalizeImageUrl(i))}" alt="${esc(c||'')}">${c?`<figcaption>${esc(c)}</figcaption>`:''}</figure>`}).join('')}</div>`}else if(type==='cta'){const u=s.buttonUrl==='mailto:'&&d.profile.email?`mailto:${d.profile.email}`:safeUrl(s.buttonUrl);body=`<div class="cta"><div><h2>${esc(tr(s,'title'))}</h2><p>${esc(tr(s,'subtitle')||tr(s,'content'))}</p></div>${tr(s,'buttonLabel')?`<a class="btn btn-primary" href="${u}">${esc(tr(s,'buttonLabel'))}</a>`:''}</div>`}else{body=sectionTitle(s)+`<div class="rich-wrap">${paragraphHtml(tr(s,'content'))}${s.imageUrl?`<img src="${esc(normalizeImageUrl(s.imageUrl))}" alt="" style="border-radius:16px;margin-top:18px">`:''}</div>`}return`<section class="${cls}" id="${esc(sectionId)}"><div class="container">${body}</div></section>`}
async function common(){setLanguageDocument();translateStatic();const d=await loadData();applyTheme(d.settings);renderNav(d.pages);const sel=document.getElementById('languageSelect');if(sel)sel.onchange=()=>{LANG=sel.value;localStorage.setItem('larbi_portfolio_language',LANG);location.reload()};const m=document.getElementById('menuBtn'),n=document.getElementById('navLinks');if(m&&n)m.addEventListener('click',()=>n.classList.toggle('open'));document.querySelectorAll('#adminLink').forEach(a=>a.href=window.PORTFOLIO_CONFIG&&window.PORTFOLIO_CONFIG.adminUrl||'#');return d}
async function renderHome(){const d=await common(),p=d.profile,s=d.settings;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||''};set('heroName',tr(p,'name'));set('heroNameSecondary',LANG==='ar'?(p.nameEn||'Tlili Mohammed Larbi'):(p.nameAr||'تليلي محمد العربي'));set('heroRole',tr(p,'role'));set('heroBio',tr(p,'bio'));set('heroBadge',tr(s,'heroBadge')||tr(p,'role'));const img=document.getElementById('profileImage');if(img){img.src=normalizeImageUrl(p.profileImageURL)||'assets/images/profile-hero.png';img.alt=tr(p,'name')}const cv=document.getElementById('cvBtn');if(cv){cv.href=safeUrl(p.cvUrl);if(!p.cvUrl)cv.style.opacity=.55}const soc=document.getElementById('socials');if(soc){const a=[];if(p.linkedin)a.push(`<a href="${safeUrl(p.linkedin)}" target="_blank">in</a>`);if(p.github)a.push(`<a href="${safeUrl(p.github)}" target="_blank">GH</a>`);if(p.email)a.push(`<a href="mailto:${esc(p.email)}">✉</a>`);if(p.whatsapp)a.push(`<a href="${safeUrl(p.whatsapp)}" target="_blank">WA</a>`);soc.innerHTML=a.join('')}const ts=document.getElementById('techStrip');if(ts)ts.innerHTML=techHtml(d.technologies);const hs=d.sections.filter(x=>(x.pageSlug||'home')==='home'&&x.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999));document.getElementById('homeSections').innerHTML=hs.map(x=>renderSection(x,d)).join('')}
async function renderPage(){const d=await common(),slug=new URLSearchParams(location.search).get('slug'),p=d.pages.find(x=>x.slug===slug&&x.published!==false),root=document.getElementById('pageRoot');if(!p){root.innerHTML=`<div class="container empty-state" style="margin-top:70px">${t('notFoundPage')}</div>`;return}document.title=tr(p,'title')+' | '+(tr(d.settings,'siteTitle')||'Larbi Portfolio');const cover=p.heroImageUrl?`<div class="page-cover"><img src="${esc(normalizeImageUrl(p.heroImageUrl))}" alt="${esc(tr(p,'title'))}"></div>`:'';root.innerHTML=`<section class="page-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><div class="project-meta">${esc(tr(p,'menuTitle')||tr(p,'title'))}</div><h1>${esc(tr(p,'heroTitle')||tr(p,'title'))}</h1><p>${esc(tr(p,'heroSubtitle'))}</p></div>${cover}</div></section>${tr(p,'content')?`<section class="section"><div class="container"><div class="rich-wrap">${paragraphHtml(tr(p,'content'))}</div></div></section>`:''}<div id="pageSections"></div>`;const ss=d.sections.filter(x=>x.pageSlug===slug&&x.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999));document.getElementById('pageSections').innerHTML=ss.map(x=>renderSection(x,d)).join('')}
async function renderProject(){const d=await common(),slug=new URLSearchParams(location.search).get('slug'),p=d.projects.find(x=>(x.slug||x.id)===slug&&x.published!==false),root=document.getElementById('projectRoot');if(!p){root.innerHTML=`<div class="container empty-state" style="margin-top:70px">${t('notFoundProject')}</div>`;return}const title=tr(p,'title');document.title=title+' | '+(tr(d.settings,'siteTitle')||'Larbi Portfolio');const links=[p.liveUrl&&`<a href="${safeUrl(p.liveUrl)}" target="_blank">${t('openProject')}</a>`,p.githubUrl&&`<a href="${safeUrl(p.githubUrl)}" target="_blank">GitHub</a>`,p.videoUrl&&`<a href="${safeUrl(p.videoUrl)}" target="_blank">${t('watchVideo')}</a>`,p.pdfUrl&&`<a href="${safeUrl(p.pdfUrl)}" target="_blank">${t('downloadReport')}</a>`].filter(Boolean).join('');root.innerHTML=`<section class="project-hero"><div class="container project-hero-grid"><div class="project-detail"><div class="project-meta">${esc(tr(p,'category'))} • ${esc(p.date||'')}</div><h1>${esc(title)}</h1><p class="lead">${esc(tr(p,'shortDescription'))}</p><div class="tags">${(p.tags||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div><div class="project-cover"><img src="${esc(imageForProject(p))}" alt="${esc(title)}"></div></div></section><section><div class="container project-content"><article class="content-card"><h2>${t('aboutProject')}</h2>${paragraphHtml(tr(p,'fullDescription')||tr(p,'shortDescription'))}${(p.gallery||[]).length?`<h2>${t('projectImages')}</h2><div class="project-gallery">${p.gallery.map(i=>`<img src="${esc(normalizeImageUrl(i))}" alt="${esc(title)}">`).join('')}</div>`:''}</article><aside class="side-card"><h3>${t('projectInfo')}</h3><p><b>${t('category')}:</b> ${esc(tr(p,'category')||'—')}</p><p><b>${t('date')}:</b> ${esc(p.date||'—')}</p><div class="link-stack">${links||`<span style="color:#8fa5b8">${t('linksLater')}</span>`}</div></aside></div></section>`}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('homeSections')?renderHome():document.getElementById('pageRoot')?renderPage():document.getElementById('projectRoot')&&renderProject()});
})();