(function(){
"use strict";
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=url=>{if(!url)return'#';try{const u=new URL(url,location.href);return['http:','https:','mailto:','tel:'].includes(u.protocol)?u.href:'#'}catch{return'#'}};
const LOCAL_IMAGES={'sis-mini-factory':'assets/images/cabinet-open.jpg','plc-esp32-motor-control':'assets/images/motor-control.jpg','fruit-vegetable-recognition':'assets/images/fruit-recognition.jpg','solar-oven':'assets/images/solar-oven.svg'};
const UI={
 en:{home:'Home',projects:'Projects',skills:'Skills',contact:'Contact',viewProjects:'View Projects',downloadCV:'Download CV',admin:'Admin',backHome:'Back to Home',loading:'Loading…',notFoundPage:'Page not found.',notFoundProject:'Project not found or not published.',noProjects:'No published projects yet.',aboutProject:'About the Project',projectImages:'Project Images',projectInfo:'Project Information',category:'Category',date:'Date',openProject:'Open Project',watchVideo:'Watch Video',downloadReport:'Download Report',linksLater:'Links will be added later.',section:'SECTION',contactEyebrow:'GET IN TOUCH',contactTitle:'Contact Me',contactSubtitle:'Have a project, collaboration opportunity or technical question? Reach me directly through the channels below.',directContact:'Direct Contact',socialNetworks:'Social Networks',sendMessage:'Send a Message',formIntro:'Fill in the form and your email application will open with the message ready to send.',formName:'Your name',formEmail:'Your email',formSubject:'Subject',formMessage:'Message',sendEmail:'Send Email',emailLabel:'Email',email2Label:'Secondary Email',phoneLabel:'Phone',phone2Label:'Secondary Phone',locationLabel:'Location',whatsappLabel:'WhatsApp',openLink:'Open profile',contactUnavailable:'Add your contact information from the administration panel.',messageSubject:'Portfolio contact request',copyLabel:'Copy',copiedLabel:'Copied'},
 fr:{home:'Accueil',projects:'Projets',skills:'Compétences',contact:'Contact',viewProjects:'Voir les projets',downloadCV:'Télécharger le CV',admin:'Administration',backHome:'Retour à l’accueil',loading:'Chargement…',notFoundPage:'Page introuvable.',notFoundProject:'Projet introuvable ou non publié.',noProjects:'Aucun projet publié.',aboutProject:'À propos du projet',projectImages:'Images du projet',projectInfo:'Informations du projet',category:'Catégorie',date:'Date',openProject:'Ouvrir le projet',watchVideo:'Voir la vidéo',downloadReport:'Télécharger le rapport',linksLater:'Les liens seront ajoutés ultérieurement.',section:'SECTION',contactEyebrow:'CONTACT',contactTitle:'Contactez-moi',contactSubtitle:'Vous avez un projet, une proposition de collaboration ou une question technique ? Contactez-moi directement via les moyens ci-dessous.',directContact:'Coordonnées directes',socialNetworks:'Réseaux sociaux',sendMessage:'Envoyer un message',formIntro:'Remplissez le formulaire : votre application e-mail s’ouvrira avec le message prêt à être envoyé.',formName:'Votre nom',formEmail:'Votre e-mail',formSubject:'Objet',formMessage:'Message',sendEmail:'Envoyer l’e-mail',emailLabel:'E-mail',email2Label:'E-mail secondaire',phoneLabel:'Téléphone',phone2Label:'Téléphone secondaire',locationLabel:'Localisation',whatsappLabel:'WhatsApp',openLink:'Ouvrir le profil',contactUnavailable:'Ajoutez vos coordonnées depuis le panneau d’administration.',messageSubject:'Demande de contact depuis le portfolio',copyLabel:'Copier',copiedLabel:'Copié'},
 ar:{home:'الرئيسية',projects:'المشاريع',skills:'المهارات',contact:'تواصل',viewProjects:'مشاهدة المشاريع',downloadCV:'تحميل CV',admin:'لوحة الإدارة',backHome:'العودة للرئيسية',loading:'جارٍ التحميل…',notFoundPage:'الصفحة غير موجودة.',notFoundProject:'المشروع غير موجود أو غير منشور.',noProjects:'لا توجد مشاريع منشورة.',aboutProject:'عن المشروع',projectImages:'صور المشروع',projectInfo:'معلومات المشروع',category:'التصنيف',date:'التاريخ',openProject:'فتح المشروع',watchVideo:'مشاهدة الفيديو',downloadReport:'تحميل التقرير',linksLater:'ستضاف الروابط لاحقًا.',section:'قسم',contactEyebrow:'تواصل مباشر',contactTitle:'تواصل معي',contactSubtitle:'لديك مشروع أو فرصة تعاون أو استفسار تقني؟ يمكنك التواصل معي مباشرة عبر الوسائل التالية.',directContact:'معلومات الاتصال',socialNetworks:'مواقع التواصل الاجتماعي',sendMessage:'إرسال رسالة',formIntro:'املأ النموذج، وسيُفتح تطبيق البريد الإلكتروني والرسالة جاهزة للإرسال.',formName:'الاسم',formEmail:'بريدك الإلكتروني',formSubject:'الموضوع',formMessage:'الرسالة',sendEmail:'إرسال البريد',emailLabel:'البريد الإلكتروني',email2Label:'البريد الإلكتروني الثاني',phoneLabel:'رقم الهاتف',phone2Label:'رقم الهاتف الثاني',locationLabel:'الموقع',whatsappLabel:'واتساب',openLink:'فتح الحساب',contactUnavailable:'أضف معلومات الاتصال من لوحة الإدارة.',messageSubject:'رسالة من موقع الأعمال',copyLabel:'نسخ',copiedLabel:'تم النسخ'}
};
let LANG=localStorage.getItem('larbi_portfolio_language')||'en';if(!['en','fr','ar'].includes(LANG))LANG='en';
const suffix={en:'En',fr:'Fr',ar:'Ar'};
function tr(o,key){if(!o)return'';return o[key+suffix[LANG]]||o[key+'En']||o[key+'Fr']||o[key+'Ar']||o[key]||''}
function t(k){return UI[LANG][k]||UI.en[k]||k}
function normalizeImageUrl(url){const v=String(url||'').trim();if(!v)return'';const ps=[/[?&]id=([A-Za-z0-9_-]{10,})/,/\/d\/([A-Za-z0-9_-]{10,})/,/googleusercontent\.com\/d\/([A-Za-z0-9_-]{10,})/];for(const p of ps){const m=v.match(p);if(m)return`https://drive.google.com/thumbnail?id=${encodeURIComponent(m[1])}&sz=w2000`}return v}

function iconSvg(name){
 const icons={
  email:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5.5h18v13H3z"/><path d="m4 7 8 6 8-6"/></svg>',
  phone:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 3.5 10 8l-2 2c1.6 3 3.1 4.5 6 6l2-2 4.5 2.8c.4.3.6.8.4 1.3-.7 1.8-2.2 3-4.2 3C9.2 21.1 2.9 14.8 2.9 7.3c0-2 1.2-3.5 3-4.2.5-.2 1 0 1.3.4Z"/></svg>',
  location:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s6-5.5 6-12a6 6 0 1 0-12 0c0 6.5 6 12 6 12Z"/><circle cx="12" cy="9" r="2.2"/></svg>',
  whatsapp:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.6a8 8 0 0 1-11.7 7.1L4 20l1.4-4.1A8 8 0 1 1 20 11.6Z"/><path d="M9 8.2c.4 2.8 2 4.5 4.9 5.6l1.4-1.2 2 1.2c-.5 1.4-1.6 2.1-3.1 2-4.3-.5-7.2-3.3-7.7-7.6 0-1.3.7-2.3 2-2.8l1.1 1.8Z"/></svg>',
  linkedin:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="7.2" cy="8" r="1.2"/><path d="M6 10.5v7M10 17.5v-7h3v1.2c.8-1 1.8-1.5 3.1-1.4 2 0 2.9 1.3 2.9 3.8v3.4"/></svg>',
  github:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 20c-4.5 1.4-4.5-2.5-6-3m12 5v-3.5c0-1 .1-1.5-.5-2.1 3.1-.3 6.4-1.5 6.4-6.8 0-1.5-.5-2.7-1.4-3.7.1-.4.6-1.8-.2-3.7 0 0-1.1-.4-3.8 1.4A13 13 0 0 0 8 3.6C5.3 1.8 4.2 2.2 4.2 2.2c-.8 1.9-.3 3.3-.2 3.7a5.3 5.3 0 0 0-1.4 3.7c0 5.3 3.3 6.5 6.4 6.8-.5.5-.8 1.2-.8 2.1V22"/></svg>',
  facebook:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 21v-8h3l.5-3H14V8.2c0-.9.3-1.5 1.7-1.5H18V4.1c-.7-.1-1.8-.2-3-.2-3 0-4.7 1.7-4.7 4.9V10H7v3h3.3v8"/></svg>',
  instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.3" cy="6.8" r="1"/></svg>',
  youtube:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 8.2c-.2-1.3-1.1-2.3-2.4-2.5C16.8 5.3 14.6 5.2 12 5.2s-4.8.1-6.6.5C4.1 5.9 3.2 6.9 3 8.2A23 23 0 0 0 3 16c.2 1.3 1.1 2.3 2.4 2.5 1.8.4 4 .5 6.6.5s4.8-.1 6.6-.5c1.3-.2 2.2-1.2 2.4-2.5a23 23 0 0 0 0-7.8Z"/><path d="m10 9 5 3-5 3Z"/></svg>',
  telegram:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m21 4-3.2 16-5.2-4-2.8 2.7.4-4.9L18 7.2 8.5 13 4 11.5Z"/></svg>'
 };
 return icons[name]||icons.email;
}
function cleanPhone(v){return String(v||'').replace(/[^\d+]/g,'')}
function whatsappHref(v){const x=String(v||'').trim();if(!x)return'#';if(/^https?:\/\//i.test(x))return safeUrl(x);const n=x.replace(/\D/g,'');return n?`https://wa.me/${n}`:'#'}
function prettyUrl(v){try{const u=new URL(v);return (u.hostname.replace(/^www\./,'')+u.pathname).replace(/\/$/,'')}catch{return String(v||'')}}

function imageForProject(p){return normalizeImageUrl(p.mainImage)||LOCAL_IMAGES[p.slug||p.id]||'assets/images/solar-oven.svg'}
function loadJsonp(url,timeout=16000){return new Promise((res,rej)=>{const cb='__larbi_'+Date.now()+'_'+Math.floor(Math.random()*1e4),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('timeout')),timeout);function done(e,d){clearTimeout(timer);try{delete window[cb]}catch{}s.remove();e?rej(e):res(d)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error('network'));s.src=url+(url.includes('?')?'&':'?')+'callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(s)})}
const FALLBACK={
 settings:{brandText:'Larbi Portfolio',accentColor:'#0aa8ff',accentColor2:'#54d4ff',siteTitleEn:'Tlili Mohammed Larbi | Engineering Portfolio',siteTitleFr:'Tlili Mohammed Larbi | Portfolio d’ingénierie',siteTitleAr:'تليلي محمد العربي | محفظة هندسية',heroBadgeEn:'Embedded Systems & Industrial Automation Engineer',heroBadgeFr:'Ingénieur en systèmes embarqués et automatisation industrielle',heroBadgeAr:'مهندس أنظمة مدمجة وأتمتة صناعية',footerTextEn:'© 2026 Tlili Mohammed Larbi. All rights reserved.',footerTextFr:'© 2026 Tlili Mohammed Larbi. Tous droits réservés.',footerTextAr:'© 2026 تليلي محمد العربي. جميع الحقوق محفوظة.'},
 profile:{nameEn:'Tlili Mohammed Larbi',nameFr:'Tlili Mohammed Larbi',nameAr:'تليلي محمد العربي',roleEn:'Embedded Systems & Industrial Automation Portfolio',roleFr:'Portfolio en systèmes embarqués et automatisation industrielle',roleAr:'مهندس أنظمة مدمجة وأتمتة صناعية',bioEn:'Embedded systems and industrial automation specialist developing practical PLC, ESP32, HMI and IoT solutions.',bioFr:'Spécialiste des systèmes embarqués et de l’automatisation industrielle, je développe des solutions pratiques basées sur PLC, ESP32, HMI et IoT.',bioAr:'متخصص في الأنظمة المدمجة والأتمتة الصناعية، أطور حلولًا عملية تجمع بين PLC وESP32 وHMI وIoT.',contactTitleEn:'Contact Me',contactTitleFr:'Contactez-moi',contactTitleAr:'تواصل معي',contactIntroEn:'Have a project, collaboration opportunity or technical question? Reach me directly through the channels below.',contactIntroFr:'Vous avez un projet, une proposition de collaboration ou une question technique ? Contactez-moi directement via les moyens ci-dessous.',contactIntroAr:'لديك مشروع أو فرصة تعاون أو استفسار تقني؟ يمكنك التواصل معي مباشرة عبر الوسائل التالية.',locationEn:'Touggourt, Algeria',locationFr:'Touggourt, Algérie',locationAr:'تقرت، الجزائر',profileImageURL:'assets/images/profile-hero.png',email:'tlilimohammedlarbi@gmail.com',email2:'',phone:'+213 557 800 962',phone2:'+213 665 433 890',github:'',linkedin:'',whatsapp:'',facebook:'',instagram:'',youtube:'',telegram:'',cvUrl:''},
 projects:[
  {id:'sis-mini-factory',slug:'sis-mini-factory',titleEn:'SIS Mini Factory',titleFr:'Mini-usine SIS',titleAr:'مصنع SIS المصغر',categoryEn:'Industrial Automation',categoryFr:'Automatisation industrielle',categoryAr:'الأتمتة الصناعية',shortDescriptionEn:'A compact smart factory control system combining PLC, HMI and ESP32.',shortDescriptionFr:'Un système compact de mini-usine intelligente combinant PLC, IHM et ESP32.',shortDescriptionAr:'نظام مصنع ذكي مصغر يجمع PLC وHMI وESP32 مع التحكم والمراقبة الصناعية.',fullDescriptionEn:'A mini smart factory integrating PLC, HMI, ESP32, physical controls, relays, sensors and web supervision.',fullDescriptionFr:'Une mini-usine intelligente intégrant PLC, IHM, ESP32, commandes physiques, relais, capteurs et supervision Web.',fullDescriptionAr:'مشروع مصنع ذكي مصغر يدمج PLC وHMI وESP32 والأزرار والريليات والحساسات مع واجهة مراقبة عبر الويب.',tags:['PLC','HMI','ESP32','Control Panel'],date:'2026',featured:true,published:true,order:1},
  {id:'plc-esp32-motor-control',slug:'plc-esp32-motor-control',titleEn:'PLC–ESP32 Motor Control',titleFr:'Commande moteur PLC–ESP32',titleAr:'نظام التحكم بمحرك PLC–ESP32',categoryEn:'IoT & Automation',categoryFr:'IoT & Automatisation',categoryAr:'إنترنت الأشياء والأتمتة',shortDescriptionEn:'Single-motor control and supervision using PLC, ESP32 and a connected dashboard.',shortDescriptionFr:'Commande et supervision d’un moteur avec PLC, ESP32 et tableau de bord connecté.',shortDescriptionAr:'مراقبة وتحكم بمحرك واحد باستخدام PLC وESP32 مع لوحة تحكم متصلة.',fullDescriptionEn:'A complete motor control system with temperature, alarms, emergency state, statistics and event logging.',fullDescriptionFr:'Système complet avec température, alarmes, urgence, statistiques et journal d’événements.',fullDescriptionAr:'نظام متكامل للتحكم في المحرك مع الحرارة والإنذارات والطوارئ والإحصائيات وتسجيل الأحداث.',tags:['PLC','ESP32','Firebase','Web Dashboard'],date:'2026',featured:true,published:true,order:2},
  {id:'fruit-vegetable-recognition',slug:'fruit-vegetable-recognition',titleEn:'Fruit & Vegetable Recognition',titleFr:'Reconnaissance des fruits et légumes',titleAr:'التعرف على الفواكه والخضروات',categoryEn:'Artificial Intelligence',categoryFr:'Intelligence artificielle',categoryAr:'الذكاء الاصطناعي',shortDescriptionEn:'A web interface that recognizes fruits and vegetables from uploaded images.',shortDescriptionFr:'Interface Web reconnaissant les fruits et légumes à partir d’images.',shortDescriptionAr:'واجهة ويب للتعرف على الفواكه والخضروات من الصور.',fullDescriptionEn:'A web application for uploading an image and classifying it with an AI model.',fullDescriptionFr:'Application Web permettant de téléverser une image et de la classifier avec un modèle d’IA.',fullDescriptionAr:'تطبيق ويب لرفع الصور وتصنيفها باستخدام نموذج ذكاء اصطناعي.',tags:['AI','CNN','Python','Web App'],date:'2026',featured:true,published:true,order:3},
  {id:'solar-oven',slug:'solar-oven',titleEn:'Solar Oven',titleFr:'Four solaire',titleAr:'الفرن الشمسي',categoryEn:'Renewable Energy',categoryFr:'Énergie renouvelable',categoryAr:'الطاقة المتجددة',shortDescriptionEn:'Solar oven design and thermal performance analysis of composite materials.',shortDescriptionFr:'Conception d’un four solaire et analyse thermique de matériaux composites.',shortDescriptionAr:'تصميم فرن شمسي ودراسة الأداء الحراري للمواد المركبة.',fullDescriptionEn:'A mobile solar oven project studying thermal storage, materials, temperature and humidity.',fullDescriptionFr:'Projet de four solaire mobile étudiant le stockage thermique, les matériaux, la température et l’humidité.',fullDescriptionAr:'مشروع فرن شمسي متنقل يدرس التخزين الحراري والمواد ودرجة الحرارة والرطوبة.',tags:['Solar Energy','Thermal Storage','Sensors'],date:'2026',featured:true,published:true,order:4}
 ],
 pages:[
  {id:'about',slug:'about',titleEn:'About',titleFr:'À propos',titleAr:'عني',menuTitleEn:'About',menuTitleFr:'À propos',menuTitleAr:'عني',heroTitleEn:'About Me',heroTitleFr:'À propos de moi',heroTitleAr:'نبذة عني',heroSubtitleEn:'My path in embedded systems and industrial automation',heroSubtitleFr:'Mon parcours en systèmes embarqués et automatisation industrielle',heroSubtitleAr:'مساري في الأنظمة المدمجة والأتمتة الصناعية',contentEn:'I am Tlili Mohammed Larbi, focused on smart industrial systems, embedded electronics and connected supervision solutions.',contentFr:'Je suis Tlili Mohammed Larbi, passionné par les systèmes industriels intelligents, l’électronique embarquée et les solutions de supervision connectées.',contentAr:'أنا تليلي محمد العربي، مهتم بتطوير الأنظمة الصناعية الذكية والإلكترونيات المدمجة وحلول المراقبة المتصلة.',published:true,showInMenu:true,menuOrder:1},
  {id:'cv',slug:'cv',titleEn:'Resume',titleFr:'CV',titleAr:'السيرة الذاتية',menuTitleEn:'Resume',menuTitleFr:'CV',menuTitleAr:'السيرة الذاتية',heroTitleEn:'Resume',heroTitleFr:'Curriculum Vitae',heroTitleAr:'السيرة الذاتية',heroSubtitleEn:'Education, skills and engineering projects',heroSubtitleFr:'Formation, compétences et projets d’ingénierie',heroSubtitleAr:'التكوين والمهارات والمشاريع الهندسية',contentEn:'Download my latest resume from the CV button on the home page.',contentFr:'Téléchargez mon CV depuis le bouton CV de la page d’accueil.',contentAr:'يمكن تحميل السيرة الذاتية من زر CV في الصفحة الرئيسية.',published:true,showInMenu:true,menuOrder:2}
 ],
 sections:[
  {id:'home-projects',pageSlug:'home',type:'projects',titleEn:'Featured Projects',titleFr:'Projets en vedette',titleAr:'أبرز المشاريع',subtitleEn:'A selection of industrial automation, embedded systems, AI and energy projects.',subtitleFr:'Une sélection de projets en automatisation industrielle, systèmes embarqués, IA et énergie.',subtitleAr:'مجموعة مختارة من مشاريع الأتمتة والأنظمة المدمجة والذكاء الاصطناعي والطاقة.',visible:true,order:1},
  {id:'home-skills',pageSlug:'home',type:'skills',titleEn:'Skills',titleFr:'Compétences',titleAr:'المهارات',subtitleEn:'Tools and technical capabilities used to design and implement systems.',subtitleFr:'Outils et compétences techniques utilisés pour concevoir et réaliser des systèmes.',subtitleAr:'الأدوات والمهارات التقنية المستخدمة في تصميم وتنفيذ الأنظمة.',visible:true,order:2},
  {id:'home-cta',pageSlug:'home',type:'cta',titleEn:'Have a project idea?',titleFr:'Vous avez une idée de projet ?',titleAr:'لديك فكرة مشروع؟',subtitleEn:'Let’s turn it into a smart and practical system.',subtitleFr:'Transformons-la en un système intelligent et pratique.',subtitleAr:'لنحوّلها إلى نظام ذكي وعملي.',buttonLabelEn:'Contact Me',buttonLabelFr:'Me contacter',buttonLabelAr:'تواصل معي',buttonUrl:'mailto:',visible:true,order:3}
 ],
 technologies:[
  {id:'plc',nameEn:'PLC',nameFr:'PLC',nameAr:'PLC',subtitleEn:'Industrial Control',subtitleFr:'Commande industrielle',subtitleAr:'التحكم الصناعي',symbol:'PLC',visible:true,order:1},
  {id:'esp32',nameEn:'ESP32',nameFr:'ESP32',nameAr:'ESP32',subtitleEn:'Embedded IoT',subtitleFr:'IoT embarqué',subtitleAr:'إنترنت الأشياء المدمج',symbol:'32',visible:true,order:2},
  {id:'hmi',nameEn:'HMI',nameFr:'IHM',nameAr:'HMI',subtitleEn:'User Interfaces',subtitleFr:'Interfaces homme-machine',subtitleAr:'واجهات المستخدم',symbol:'HMI',visible:true,order:3},
  {id:'firebase',nameEn:'Firebase',nameFr:'Firebase',nameAr:'Firebase',subtitleEn:'Realtime Database',subtitleFr:'Base de données temps réel',subtitleAr:'قاعدة بيانات فورية',symbol:'FB',visible:true,order:4},
  {id:'matlab',nameEn:'MATLAB/Simulink',nameFr:'MATLAB/Simulink',nameAr:'MATLAB/Simulink',subtitleEn:'Modeling & Simulation',subtitleFr:'Modélisation et simulation',subtitleAr:'النمذجة والمحاكاة',symbol:'M',visible:true,order:5}
 ],
 skillGroups:[
  {id:'automation',titleEn:'Automation & Control',titleFr:'Automatisation & Commande',titleAr:'الأتمتة والتحكم',iconText:'AUTO',visible:true,order:1},
  {id:'embedded',titleEn:'Embedded Systems',titleFr:'Systèmes embarqués',titleAr:'الأنظمة المدمجة',iconText:'MCU',visible:true,order:2},
  {id:'web-iot',titleEn:'Web & IoT',titleFr:'Web & IoT',titleAr:'الويب وإنترنت الأشياء',iconText:'IoT',visible:true,order:3},
  {id:'software',titleEn:'Software & Tools',titleFr:'Logiciels & Outils',titleAr:'البرامج والأدوات',iconText:'DEV',visible:true,order:4}
 ],
 skills:[
  {id:'plc-programming',groupId:'automation',nameEn:'PLC Programming',nameFr:'Programmation PLC',nameAr:'برمجة PLC',visible:true,order:1},{id:'panel-design',groupId:'automation',nameEn:'Control Panel Design',nameFr:'Conception d’armoires',nameAr:'تصميم خزائن التحكم',visible:true,order:2},{id:'sensors',groupId:'automation',nameEn:'Sensors & Actuators',nameFr:'Capteurs & Actionneurs',nameAr:'الحساسات والمشغلات',visible:true,order:3},{id:'hmi-systems',groupId:'automation',nameEn:'HMI Systems',nameFr:'Systèmes IHM',nameAr:'أنظمة HMI',visible:true,order:4},
  {id:'esp32-arduino',groupId:'embedded',nameEn:'ESP32 / Arduino',nameFr:'ESP32 / Arduino',nameAr:'ESP32 / Arduino',visible:true,order:1},{id:'cpp',groupId:'embedded',nameEn:'C / C++',nameFr:'C / C++',nameAr:'C / C++',visible:true,order:2},{id:'microcontrollers',groupId:'embedded',nameEn:'Microcontrollers',nameFr:'Microcontrôleurs',nameAr:'المتحكمات الدقيقة',visible:true,order:3},{id:'realtime',groupId:'embedded',nameEn:'Real-time Monitoring',nameFr:'Supervision temps réel',nameAr:'المراقبة في الزمن الحقيقي',visible:true,order:4},
  {id:'web-dashboards',groupId:'web-iot',nameEn:'Web Dashboards',nameFr:'Tableaux de bord Web',nameAr:'لوحات تحكم الويب',visible:true,order:1},{id:'firebase-skill',groupId:'web-iot',nameEn:'Firebase',nameFr:'Firebase',nameAr:'Firebase',visible:true,order:2},{id:'iot-comms',groupId:'web-iot',nameEn:'IoT Communication',nameFr:'Communication IoT',nameAr:'اتصالات إنترنت الأشياء',visible:true,order:3},{id:'html-css-js',groupId:'web-iot',nameEn:'HTML / CSS / JavaScript',nameFr:'HTML / CSS / JavaScript',nameAr:'HTML / CSS / JavaScript',visible:true,order:4},
  {id:'matlab-skill',groupId:'software',nameEn:'MATLAB / Simulink',nameFr:'MATLAB / Simulink',nameAr:'MATLAB / Simulink',visible:true,order:1},{id:'machine-expert',groupId:'software',nameEn:'Machine Expert Basic',nameFr:'Machine Expert Basic',nameAr:'Machine Expert Basic',visible:true,order:2},{id:'vijeo',groupId:'software',nameEn:'Vijeo Designer',nameFr:'Vijeo Designer',nameAr:'Vijeo Designer',visible:true,order:3},{id:'proteus-see',groupId:'software',nameEn:'Proteus / SEE Electrical',nameFr:'Proteus / SEE Electrical',nameAr:'Proteus / SEE Electrical',visible:true,order:4}
 ]
};
function usableArray(value,fallback){return Array.isArray(value)&&value.length?value:fallback}
async function loadData(){const u=window.PORTFOLIO_CONFIG&&window.PORTFOLIO_CONFIG.apiUrl;if(!u)return FALLBACK;try{const d=await loadJsonp(u);if(!d||!d.ok)throw new Error('Invalid API response');return{settings:Object.assign({},FALLBACK.settings,d.settings||{}),profile:Object.assign({},FALLBACK.profile,d.profile||{}),projects:usableArray(d.projects,FALLBACK.projects),pages:usableArray(d.pages,FALLBACK.pages),sections:usableArray(d.sections,FALLBACK.sections),technologies:usableArray(d.technologies,FALLBACK.technologies),skillGroups:usableArray(d.skillGroups,FALLBACK.skillGroups),skills:usableArray(d.skills,FALLBACK.skills)}}catch(e){console.warn('Portfolio API fallback:',e);return FALLBACK}}
function setLanguageDocument(){document.documentElement.lang=LANG;document.documentElement.dir=LANG==='ar'?'rtl':'ltr';const sel=document.getElementById('languageSelect');if(sel)sel.value=LANG}
function applyTheme(s){if(s.accentColor)document.documentElement.style.setProperty('--primary',s.accentColor);if(s.accentColor2)document.documentElement.style.setProperty('--primary2',s.accentColor2);document.title=tr(s,'siteTitle')||'Larbi Portfolio';document.querySelectorAll('#brandText').forEach(x=>x.textContent=s.brandText||'Larbi Portfolio');document.querySelectorAll('#footerText').forEach(x=>x.textContent=tr(s,'footerText'));}
function translateStatic(){const map={navHome:'home',navProjects:'projects',navSkills:'skills',navContact:'contact',projectsButton:'viewProjects',cvBtn:'downloadCV',adminLink:'admin',backHome:'backHome'};Object.keys(map).forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=t(map[id])});document.querySelectorAll('[data-loading]').forEach(e=>e.textContent=t('loading'));}
function renderNav(pages){const html=pages.filter(p=>p.published!==false&&p.showInMenu!==false&&p.slug!=='contact').sort((a,b)=>(a.menuOrder||999)-(b.menuOrder||999)).map(p=>`<a href="page.html?slug=${encodeURIComponent(p.slug)}">${esc(tr(p,'menuTitle')||tr(p,'title'))}</a>`).join('');document.querySelectorAll('#dynamicNav').forEach(x=>x.innerHTML=html)}
function parseLines(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}function paragraphHtml(v){return parseLines(v).map(x=>`<p>${esc(x)}</p>`).join('')}
function techHtml(items){return items.filter(x=>x.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999)).map(x=>{const name=tr(x,'name'),sub=tr(x,'subtitle'),visual=x.logoUrl?`<img class="tech-logo" src="${esc(normalizeImageUrl(x.logoUrl))}" alt="${esc(name)}">`:`<span>${esc(x.symbol||name.slice(0,3))}</span>`;const inner=`<div class="tech-icon">${visual}</div><div><strong>${esc(name)}</strong><small>${esc(sub)}</small></div>`;return x.linkUrl?`<a class="tech-chip" href="${safeUrl(x.linkUrl)}" target="_blank">${inner}</a>`:`<div class="tech-chip">${inner}</div>`}).join('')}
function projectCard(p){const title=tr(p,'title'),category=tr(p,'category'),short=tr(p,'shortDescription');return`<a class="project-card" href="project.html?slug=${encodeURIComponent(p.slug||p.id)}"><div class="project-image"><img src="${esc(imageForProject(p))}" alt="${esc(title)}" onerror="this.src='${esc(LOCAL_IMAGES[p.slug||p.id]||'assets/images/solar-oven.svg')}'"></div><div class="project-body"><span class="project-category">${esc(category)}</span><h3>${esc(title)}</h3><p>${esc(short)}</p><div class="tags">${(p.tags||[]).slice(0,4).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div></a>`}
function typeLabel(type){const labels={projects:{en:'PROJECTS',fr:'PROJETS',ar:'المشاريع'},skills:{en:'SKILLS',fr:'COMPÉTENCES',ar:'المهارات'},cards:{en:'CARDS',fr:'CARTES',ar:'بطاقات'},rich:{en:'CONTENT',fr:'CONTENU',ar:'محتوى'},stats:{en:'STATS',fr:'STATISTIQUES',ar:'إحصائيات'},timeline:{en:'TIMELINE',fr:'PARCOURS',ar:'المسار'},gallery:{en:'GALLERY',fr:'GALERIE',ar:'معرض'},cta:{en:'CONTACT',fr:'CONTACT',ar:'تواصل'}};return(labels[type]&&labels[type][LANG])||t('section')}
function sectionTitle(s){return`<div class="section-title"><span class="kicker">${esc(typeLabel(s.type))}</span><h2>${esc(tr(s,'title'))}</h2>${tr(s,'subtitle')?`<p>${esc(tr(s,'subtitle'))}</p>`:''}</div>`}
function skillsHtml(groups,skills){return groups.filter(g=>g.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999)).map(g=>{const items=skills.filter(s=>s.visible!==false&&s.groupId===g.id).sort((a,b)=>(a.order||999)-(b.order||999));const icon=g.iconUrl?`<img src="${esc(normalizeImageUrl(g.iconUrl))}" alt="">`:`<span>${esc(g.iconText||'•')}</span>`;return`<article class="skill-box"><div class="skill-title-row"><div class="skill-group-icon">${icon}</div><h3>${esc(tr(g,'title'))}</h3></div><ul>${items.map(s=>`<li>${s.iconUrl?`<img class="skill-item-icon" src="${esc(normalizeImageUrl(s.iconUrl))}" alt="">`:''}${esc(tr(s,'name'))}</li>`).join('')}</ul></article>`}).join('')}
function renderSection(s,d){const type=s.type||'rich',cls='section',sectionId=(s.pageSlug==='home'&&type==='cta')?'contact':(s.id||type);let body='';if(type==='projects'){const ps=d.projects.filter(p=>p.published!==false&&p.featured!==false).sort((a,b)=>(a.order||999)-(b.order||999));body=sectionTitle(s)+`<div class="projects-grid" id="projects">${ps.length?ps.map(projectCard).join(''):`<div class="empty-state">${t('noProjects')}</div>`}</div>`}else if(type==='skills'){body=sectionTitle(s)+`<div class="skills-grid" id="skills">${skillsHtml(d.skillGroups,d.skills)}</div>`}else if(type==='cards'){body=sectionTitle(s)+`<div class="cards-grid">${parseLines(tr(s,'itemsText')).map(l=>{const[a,b,img,url,tags]=l.split('|'),inner=`${img?`<img src="${esc(normalizeImageUrl(img))}" alt="">`:''}<h3>${esc(a||'')}</h3><p>${esc(b||'')}</p>${tags?`<div class="tags">${tags.split(';').map(x=>`<span class="tag">${esc(x.trim())}</span>`).join('')}</div>`:''}`;return url?`<a class="generic-card" href="${safeUrl(url)}">${inner}</a>`:`<article class="generic-card">${inner}</article>`}).join('')}</div>`}else if(type==='stats'){body=sectionTitle(s)+`<div class="stats-grid">${parseLines(tr(s,'itemsText')).map(l=>{const[n,a]=l.split('|');return`<div class="stat-card"><strong>${esc(n||'')}</strong><span>${esc(a||'')}</span></div>`}).join('')}</div>`}else if(type==='timeline'){body=sectionTitle(s)+`<div class="timeline">${parseLines(tr(s,'itemsText')).map(l=>{const[y,a,b]=l.split('|');return`<article class="timeline-item"><div class="timeline-year">${esc(y||'')}</div><div><h3>${esc(a||'')}</h3><p>${esc(b||'')}</p></div></article>`}).join('')}</div>`}else if(type==='gallery'){body=sectionTitle(s)+`<div class="gallery-grid">${parseLines(tr(s,'itemsText')).map(l=>{const[i,c]=l.split('|');return`<figure class="gallery-item"><img src="${esc(normalizeImageUrl(i))}" alt="${esc(c||'')}">${c?`<figcaption>${esc(c)}</figcaption>`:''}</figure>`}).join('')}</div>`}else if(type==='cta'){const u=s.buttonUrl==='mailto:'?'contact.html':safeUrl(s.buttonUrl);body=`<div class="cta"><div><h2>${esc(tr(s,'title'))}</h2><p>${esc(tr(s,'subtitle')||tr(s,'content'))}</p></div>${tr(s,'buttonLabel')?`<a class="btn btn-primary" href="${u}">${esc(tr(s,'buttonLabel'))}</a>`:''}</div>`}else{body=sectionTitle(s)+`<div class="rich-wrap">${paragraphHtml(tr(s,'content'))}${s.imageUrl?`<img src="${esc(normalizeImageUrl(s.imageUrl))}" alt="" style="border-radius:16px;margin-top:18px">`:''}</div>`}return`<section class="${cls}" id="${esc(sectionId)}"><div class="container">${body}</div></section>`}
let PENDING_HASH=location.hash||'';
function closeMobileMenu(){const n=document.getElementById('navLinks');if(n)n.classList.remove('open')}
function scrollToHash(hash){if(!hash||hash==='#')return false;const id=decodeURIComponent(hash.slice(1));const target=document.getElementById(id);if(!target)return false;target.scrollIntoView({behavior:'smooth',block:'start'});return true}
function setupNavigation(){document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const href=a.getAttribute('href')||'';if(href.startsWith('#')){PENDING_HASH=href;const found=scrollToHash(href);if(found)e.preventDefault();closeMobileMenu()}else if(a.closest('#navLinks'))closeMobileMenu()})}
async function common(){setLanguageDocument();translateStatic();setupNavigation();const d=await loadData();applyTheme(d.settings);renderNav(d.pages);const sel=document.getElementById('languageSelect');if(sel)sel.onchange=()=>{LANG=sel.value;localStorage.setItem('larbi_portfolio_language',LANG);location.reload()};const m=document.getElementById('menuBtn'),n=document.getElementById('navLinks');if(m&&n)m.addEventListener('click',()=>n.classList.toggle('open'));document.querySelectorAll('#adminLink').forEach(a=>a.href=window.PORTFOLIO_CONFIG&&window.PORTFOLIO_CONFIG.adminUrl||'#');return d}
async function renderHome(){const d=await common(),p=d.profile,s=d.settings;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v||''};set('heroName',tr(p,'name'));set('heroNameSecondary',LANG==='ar'?(p.nameEn||'Tlili Mohammed Larbi'):(p.nameAr||'تليلي محمد العربي'));set('heroRole',tr(p,'role'));set('heroBio',tr(p,'bio'));set('heroBadge',tr(s,'heroBadge')||tr(p,'role'));const img=document.getElementById('profileImage');if(img){img.src=normalizeImageUrl(p.profileImageURL)||'assets/images/profile-hero.png';img.alt=tr(p,'name')}const cv=document.getElementById('cvBtn');if(cv){cv.href=safeUrl(p.cvUrl);if(!p.cvUrl)cv.style.opacity=.55}const soc=document.getElementById('socials');if(soc){const a=[];if(p.linkedin)a.push(`<a class="social-icon-link" href="${safeUrl(p.linkedin)}" target="_blank" aria-label="LinkedIn">${iconSvg('linkedin')}</a>`);if(p.github)a.push(`<a class="social-icon-link" href="${safeUrl(p.github)}" target="_blank" aria-label="GitHub">${iconSvg('github')}</a>`);if(p.email)a.push(`<a class="social-icon-link" href="mailto:${esc(p.email)}" aria-label="Email">${iconSvg('email')}</a>`);if(p.whatsapp)a.push(`<a class="social-icon-link" href="${whatsappHref(p.whatsapp)}" target="_blank" aria-label="WhatsApp">${iconSvg('whatsapp')}</a>`);soc.innerHTML=a.join('')}const ts=document.getElementById('techStrip');if(ts)ts.innerHTML=techHtml(d.technologies);const hs=d.sections.filter(x=>(x.pageSlug||'home')==='home'&&x.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999));document.getElementById('homeSections').innerHTML=hs.map(x=>renderSection(x,d)).join('');requestAnimationFrame(()=>{if(PENDING_HASH)scrollToHash(PENDING_HASH)})}
async function renderPage(){const d=await common(),slug=new URLSearchParams(location.search).get('slug'),p=d.pages.find(x=>x.slug===slug&&x.published!==false),root=document.getElementById('pageRoot');if(!p){root.innerHTML=`<div class="container empty-state" style="margin-top:70px">${t('notFoundPage')}</div>`;return}document.title=tr(p,'title')+' | '+(tr(d.settings,'siteTitle')||'Larbi Portfolio');const cover=p.heroImageUrl?`<div class="page-cover"><img src="${esc(normalizeImageUrl(p.heroImageUrl))}" alt="${esc(tr(p,'title'))}"></div>`:'';root.innerHTML=`<section class="page-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><div class="project-meta">${esc(tr(p,'menuTitle')||tr(p,'title'))}</div><h1>${esc(tr(p,'heroTitle')||tr(p,'title'))}</h1><p>${esc(tr(p,'heroSubtitle'))}</p></div>${cover}</div></section>${tr(p,'content')?`<section class="section"><div class="container"><div class="rich-wrap">${paragraphHtml(tr(p,'content'))}</div></div></section>`:''}<div id="pageSections"></div>`;const ss=d.sections.filter(x=>x.pageSlug===slug&&x.visible!==false).sort((a,b)=>(a.order||999)-(b.order||999));document.getElementById('pageSections').innerHTML=ss.map(x=>renderSection(x,d)).join('')}

function contactInfoCard(kind,label,value,href){
 if(!value)return'';
 return`<a class="contact-info-card" href="${esc(href)}"${/^https?:/i.test(href)?' target="_blank" rel="noopener"':''}><span class="contact-icon">${iconSvg(kind)}</span><span class="contact-card-copy"><small>${esc(label)}</small><strong dir="ltr">${esc(value)}</strong></span><span class="contact-arrow">↗</span></a>`;
}
function socialCard(kind,label,url){
 if(!url)return'';
 return`<a class="social-network-card social-${esc(kind)}" href="${safeUrl(url)}" target="_blank" rel="noopener"><span class="social-network-icon">${iconSvg(kind)}</span><span><strong>${esc(label)}</strong><small dir="ltr">${esc(prettyUrl(url))}</small></span><b>↗</b></a>`;
}
async function renderContact(){
 const d=await common(),p=d.profile,root=document.getElementById('contactRoot');
 const locationText=tr(p,'location');
 const info=[
  contactInfoCard('email',t('emailLabel'),p.email,p.email?`mailto:${p.email}`:'#'),
  contactInfoCard('email',t('email2Label'),p.email2,p.email2?`mailto:${p.email2}`:'#'),
  contactInfoCard('phone',t('phoneLabel'),p.phone,p.phone?`tel:${cleanPhone(p.phone)}`:'#'),
  contactInfoCard('phone',t('phone2Label'),p.phone2,p.phone2?`tel:${cleanPhone(p.phone2)}`:'#'),
  contactInfoCard('whatsapp',t('whatsappLabel'),p.whatsapp,whatsappHref(p.whatsapp)),
  contactInfoCard('location',t('locationLabel'),locationText,locationText?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(locationText):'#')
 ].filter(Boolean).join('');
 const social=[
  socialCard('linkedin','LinkedIn',p.linkedin),
  socialCard('github','GitHub',p.github),
  socialCard('facebook','Facebook',p.facebook),
  socialCard('instagram','Instagram',p.instagram),
  socialCard('youtube','YouTube',p.youtube),
  socialCard('telegram','Telegram',p.telegram)
 ].filter(Boolean).join('');
 const title=tr(p,'contactTitle')||t('contactTitle');
 const intro=tr(p,'contactIntro')||t('contactSubtitle');
 document.title=`${title} | ${tr(d.settings,'siteTitle')||'Larbi Portfolio'}`;
 root.innerHTML=`<section class="contact-hero"><span class="hero-dots"></span><div class="container contact-hero-inner"><div class="contact-kicker">${t('contactEyebrow')}</div><h1>${esc(title)}</h1><p>${esc(intro)}</p></div></section>
 <section class="contact-section"><div class="container contact-layout">
  <div class="contact-left">
   <div class="contact-block"><div class="contact-heading"><span></span><h2>${t('directContact')}</h2></div><div class="contact-info-grid">${info||`<div class="empty-state">${t('contactUnavailable')}</div>`}</div></div>
   <div class="contact-block"><div class="contact-heading"><span></span><h2>${t('socialNetworks')}</h2></div><div class="social-network-grid">${social||`<div class="empty-state">${t('contactUnavailable')}</div>`}</div></div>
  </div>
  <form class="contact-form-card" id="contactForm">
   <div class="contact-heading"><span></span><h2>${t('sendMessage')}</h2></div>
   <p>${t('formIntro')}</p>
   <div class="contact-form-grid">
    <label><span>${t('formName')}</span><input name="name" required autocomplete="name"></label>
    <label><span>${t('formEmail')}</span><input name="email" type="email" required autocomplete="email"></label>
    <label class="full"><span>${t('formSubject')}</span><input name="subject" required></label>
    <label class="full"><span>${t('formMessage')}</span><textarea name="message" required></textarea></label>
   </div>
   <button class="btn btn-primary contact-submit" type="submit"${p.email?'':' disabled'}>${iconSvg('email')}<span>${t('sendEmail')}</span></button>
  </form>
 </div></section>`;
 const form=document.getElementById('contactForm');
 if(form&&p.email)form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),subject=String(fd.get('subject')||t('messageSubject')),body=`${t('formName')}: ${fd.get('name')}\n${t('formEmail')}: ${fd.get('email')}\n\n${fd.get('message')}`;location.href=`mailto:${encodeURIComponent(p.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
}

async function renderProject(){const d=await common(),slug=new URLSearchParams(location.search).get('slug'),p=d.projects.find(x=>(x.slug||x.id)===slug&&x.published!==false),root=document.getElementById('projectRoot');if(!p){root.innerHTML=`<div class="container empty-state" style="margin-top:70px">${t('notFoundProject')}</div>`;return}const title=tr(p,'title');document.title=title+' | '+(tr(d.settings,'siteTitle')||'Larbi Portfolio');const links=[p.liveUrl&&`<a href="${safeUrl(p.liveUrl)}" target="_blank">${t('openProject')}</a>`,p.githubUrl&&`<a href="${safeUrl(p.githubUrl)}" target="_blank">GitHub</a>`,p.videoUrl&&`<a href="${safeUrl(p.videoUrl)}" target="_blank">${t('watchVideo')}</a>`,p.pdfUrl&&`<a href="${safeUrl(p.pdfUrl)}" target="_blank">${t('downloadReport')}</a>`].filter(Boolean).join('');root.innerHTML=`<section class="project-hero"><div class="container project-hero-grid"><div class="project-detail"><div class="project-meta">${esc(tr(p,'category'))} • ${esc(p.date||'')}</div><h1>${esc(title)}</h1><p class="lead">${esc(tr(p,'shortDescription'))}</p><div class="tags">${(p.tags||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div><div class="project-cover"><img src="${esc(imageForProject(p))}" alt="${esc(title)}"></div></div></section><section><div class="container project-content"><article class="content-card"><h2>${t('aboutProject')}</h2>${paragraphHtml(tr(p,'fullDescription')||tr(p,'shortDescription'))}${(p.gallery||[]).length?`<h2>${t('projectImages')}</h2><div class="project-gallery">${p.gallery.map(i=>`<img src="${esc(normalizeImageUrl(i))}" alt="${esc(title)}">`).join('')}</div>`:''}</article><aside class="side-card"><h3>${t('projectInfo')}</h3><p><b>${t('category')}:</b> ${esc(tr(p,'category')||'—')}</p><p><b>${t('date')}:</b> ${esc(p.date||'—')}</p><div class="link-stack">${links||`<span style="color:#8fa5b8">${t('linksLater')}</span>`}</div></aside></div></section>`}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('homeSections')?renderHome():document.getElementById('contactRoot')?renderContact():document.getElementById('pageRoot')?renderPage():document.getElementById('projectRoot')&&renderProject()});
})();